### ISSUE TITLE
Consider creating a new release and corresponding and nuget package

### ISSUE THREAD

**Issue by motivity-chris** [tpeczek/Lib.AspNetCore.WebSocketsCompression#3]
Thank you for spending your time on this project, which provides a lot of value in our project.

Does commit dae44e8 represent a complete fix/feature that should be released?

If so, we hope you might consider creating a new release and corresponding nuget package, as this would allow users like ourselves to more easily leverage your work as a dependency.

Thank you!

**Comment by tpeczek** [comment]
@motivity-chris So far I haven't received too much feedback on this project. Also the NuGet stats doesn't suggest huge interest. In the result this one has a low priority on my list and consist some unfinished work.

That said, if you have real interest in this project I'm willing to put some investment into it. In order to do that I would have to upgrade to .NET Standard 2.0 and ASP.NET Core 2.0.0. Would that be a problem for your project?

**Comment by motivity-chris** [comment]
We don't suspect that any issues there -- thanks for considering us.

I would like to mention, however, _if_ you were to consider investing additional time expanding this project and were receptive to ideas/suggestions, that we are limited by the incompatibility of the library (and the demo app) with Chrome.  Having that compatibility (ideally, of course, Edge/Chrome/iOS/Android compatibility) would be very useful to our project in particular.

In any case, thanks again for making this effort available!

**Comment by tpeczek** [comment]
What do you mean by "incompatibility with Chrome"? When I was still working on this, the demo project has been tested with Edge, Chrome and FireFox with no issues (well the compression doesn't work in Edge but thats because Edge doesn't support it).

In general this is just a wrapper around WebSockets support from ASP.NET Core, so any incompatibilities here would suggest incompatibilities there which I haven't heard about.

If you have hit any specific issue please share details so I can investigate.

**Comment by motivity-chris** [comment]
I created a more complete report regarding the demo app at tpeczek/Demo.AspNetCore.WebSockets#2.

Thank you again for taking the time to consider these issues!

**Comment by tpeczek** [comment]
I'll take a look at it at my first convenience, but it might take some time.

**Comment by tpeczek** [comment]
Closing as project is being archived in favor of built-in [WebSocket compression](https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-6/#websocket-compression) coming in ASP.NET Core 6.
